management:
  metrics:
    export:
      influx:
        enabled: true
        db: springboot
        uri: http://192.168.25.130:8086
        #        user-name:
        #        password:
        connect-timeout: 1s
        read-timeout: 10s
        auto-create-db: true
        step: 1m
        num-threads: 2
        consistency: one
        compressed: true
        batch-size: 10000

socket:
  host: 127.0.0.1
  port: 8989